Repository Lazarus-org/api-response-shaper, pull requests merged in 2024-10, with the labels that each got.

#15 ✨ Add DynamicResponseMiddleware
  pyproject.toml
  response_shaper/middleware.py
Labels: enhancement

#16 🔧 ✨ Add settings for validate package configs
  response_shaper/settings/__init__.py
  response_shaper/settings/check.py
  response_shaper/settings/conf.py
Labels: enhancement

#17 🚨 Add test for settings and middleware
  pyproject.toml
  response_shaper/tests/conftest.py
  response_shaper/tests/test_middleware.py
  response_shaper/tests/test_settings.py
Labels: test

#18 💚 Update CI config and README
  .github/workflows/ci.yml
  README.md
Labels: configuration

#19 ⚡ 🔨 refactor: Fix missing type annotations
  response_shaper/decorators.py
  response_shaper/settings/conf.py
  response_shaper/tests/conftest.py
  response_shaper/tests/constants.py
  response_shaper/tests/setup.py
  response_shaper/tests/test_api_responses.py
  response_shaper/tests/test_decorators.py
  response_shaper/tests/test_middleware.py
  response_shaper/tests/test_settings.py
Labels: refactor

#20 Feat/docs
  AUTHORS.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  CONTRIBUTORS.md
  README.md
  SECURITY.md
Labels: documentation

#23 ⚡ 🔨 refactor(middleware): Improve generic exceptions
  README.md
  response_shaper/middleware.py
  response_shaper/tests/test_middleware.py
Labels: enhancement, test

#25 🔧 chore: Add support for py3.13 and drop support py 3.8
  .github/workflows/ci.yml
  README.md
  packages/requirements-dev.txt
  packages/requirements.txt
  poetry.lock
  pyproject.toml
  response_shaper/tests/constants.py
  tox.ini
Labels: configuration
